### ISSUE TITLE
Version Pt-Br Cards

### ISSUE THREAD

**Issue by sieb** [TheSCInitiative/BOINC-Promotion-and-Flyers#1]
This is the first Brazilian Portuguese version of the BOINC General-1 card I made. I changed the translation of "spare computational power" to "idle time" (tempo ocioso) which makes more sense in our language.
![BOINC General-1_Pt-Br](https://github.com/TheSCInitiative/BOINC-Promotion-and-Flyers/assets/19733946/0407021c-a63c-4064-8b42-c5fee0657be9)

**Comment by makeasnek** [comment]
Awesome, I'll add it to the repo now. Thank you!
